### ISSUE TITLE
apt-get issues / IP Issues

### ISSUE THREAD

**Issue by IBNobody** [coolboiime/tunnelChecker#1]
I seem to be having two separate issues with this setup and the latest build of the container. When I try to run the tunchecker_helper on a working container, I get...

```
Installing nmap ...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch http://build.openvpn.net/debian/openvpn/stable/dists/xenial/InRelease  Temporary failure resolving 'build.openvpn.net'
W: Failed to fetch http://ppa.launchpad.net/transmissionbt/ppa/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to locate package nmap
/data/tunchecker.sh: line 19: nmap: command not found
Interface IP is 10.10.0.4
API Query IP is 96.xx.xx.xx
Network Port is closed
Killing OpenVPN
```

So aside from the issue installing nmap (which stems from running apt-get), I also have my interface IP not matching my Query IP.

For reference, this is the command I run to install/start my container...

```
docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/apps/configs/transmissionVPN/openVPN/mullvad_us-tx.ovpn:/etc/openvpn/custom/default.ovpn \
    -v /volume1/apps/configs/transmissionVPN/openVPN:/etc/openvpn/custom/ \
    -v /etc/localtime:/etc/localtime:ro \
    -v /volume1/download/_watch/transmission:/watch \
    -v /volume1/download/_incomplete/transmission:/incomplete \
    -v /volume1/download:/downloads \
    -v /volume1/apps/transmissionVPN:/data \
    -v /volume1/apps/configs/transmissionVPN/resolv.conf:/etc/resolv.conf \
    -e "OPENVPN_PROVIDER=CUSTOM" \
    -e "OPENVPN_CONFIG=mullvad_us-tx" \
    -e "OPENVPN_USERNAME=xxx" \
    -e "OPENVPN_PASSWORD=xxx" \
    -e "LOCAL_NETWORK=192.168.xxx.xxx/24" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore \"ping\"" \
    -e "PGID=101" \
    -e "PUID=1028" \
    -e "TRANSMISSION_PEER_PORT=yyy" \
    -e "TRANSMISSION_PORT_FORWARDING_ENABLED=false" \
    -e "TRANSMISSION_DOWNLOAD_DIR=/downloads" \
    -e "TRANSMISSION_INCOMPLETE_DIR=/incomplete" \
    -e "TRANSMISSION_WATCH_DIR=/watch" \
    -e "TRANSMISSION_HOME=/data" \
    -e "TRANSMISSION_RPC_ENABLED=true" \
    -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
    -e "TRANSMISSION_RPC_PASSWORD=xxx" \
    -e "TRANSMISSION_RPC_USERNAME=xxx" \
    -p xxx:xxx \
    -p yyy:yyy \
    --dns 8.8.8.8 \
    --dns 8.8.4.4 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "TransmissionVPN" \
    haugene/transmission-openvpn:latest
```

I'm running on a Synology NAS which has some hoops to jump through (hence my manual docker command).

(As an aside, if you leave the `PORT_FORWARD` field blank,  could you also skip the installation of nmap?)

**Comment by coolboiime** [comment]
Is your container getting internet? `apt-get` isn’t supposed to fail on updating..

**Comment by coolboiime** [comment]
I can do some edits on not requiring nmap installation when the `PORT_FORWARD` field isn’t set.

**Comment by IBNobody** [comment]
> Is your container getting internet? apt-get isn’t supposed to fail on updating.

Yeah, it works fine, aside from the issue your script is resolving.

> If you can't compare IPs, you can do a wget to check if a particular website is working. If it doesn't, then the script assumes the VPN internet is down.

Ok, yeah. Also, I will try to create a failed state and see what `VPN_RESP=`curl -sS --interface tun0 http://ipinfo.io/ip` generates.

> For the port forward setting, I have updated the source to skip nmap installation for those not using port forward checks.

:)

**Comment by coolboiime** [comment]
`VPN_RESP` by default will throw a lot of curl errors when the VPN internet is i accessible. The reason why it works is because the errors don’t match an IP address.

I found something that could be of help:
https://stackoverflow.com/questions/2924422/how-do-i-determine-if-a-web-page-exists-with-shell-scripting

**Comment by IBNobody** [comment]
Ok, so I was able to get the unit in a failing state, and the result is... 

```
docker exec TransmissionVPN curl -sS http://ipinfo.io/ip
curl: (6) Could not resolve host: ipinfo.io
```

I changed the killscript's decision statement to the following and am evaluating it right now.

     if [ -z "$VPN_RESP" ] || [ "$VPN_PORT" = "closed" ]; then

**Comment by IBNobody** [comment]
1+ month in, and this script is still working like a charm. I even can see in my Synology logs when the container gets rebooted. Thank you again, @coolboiime

**Comment by coolboiime** [comment]
@IBNobody Glad to be of help!!
